name = "common-lisp"
entrypoint = "main.lisp"
extensions = [
  "asd",
  "lisp"
]
aliases = ["cl", "lisp"]

packages = [
  "cl-quicklisp",
  "sbcl"
]
setup = [
  "sbcl --non-interactive --load /usr/share/cl-quicklisp/quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))'"
]

versionCommand = [
  "sbcl",
  "--version"
]

[run]
command = [
  "sbcl",
  "--load",
  "./main"
]

[tests]

  [tests.hello]
  code = "(format t \"hello world~%\")"
  output = "This is SBCL 1.4.5.debian, an implementation of ANSI Common Lisp.\nMore information about SBCL is available at <http://www.sbcl.org/>.\n\nSBCL is free software, provided as is, with absolutely no warranty.\nIt is mostly in the public domain; some portions are provided under\nBSD-style licenses.  See the CREDITS and COPYING files in the\ndistribution for more information.\nhello world\n* "
